import type { WorldDef } from "../types";

export const world: WorldDef = {
  id: "robo-basics",
  emoji: "🤖",
  color: "#f59e0b",
  title: { en: "Robo Basics", id: "Dasar Robo" },
  description: {
    en: "Meet Robo! Learn how computers follow steps, commands and patterns.",
    id: "Kenalan dengan Robo! Pelajari cara komputer mengikuti langkah, perintah, dan pola.",
  },
  levels: [
    {
      id: "commands",
      emoji: "🎯",
      color: "#10b981",
      title: { en: "Precise Commands", id: "Perintah yang Tepat" },
      description: {
        en: "Robots only do EXACTLY what you say. Guide Robo to the star with movement blocks!",
        id: "Robot hanya melakukan PERSIS yang kamu perintahkan. Antar Robo ke bintang dengan balok perintah!",
      },
      games: [
        {
          kind: "robot",
          id: "cmd-first-steps",
          emoji: "👣",
          title: { en: "First Steps", id: "Langkah Pertama" },
          instructions: {
            en: "Add arrow blocks to walk Robo to the star, then press Go!",
            id: "Tambahkan balok panah untuk mengantar Robo ke bintang, lalu tekan Jalan!",
          },
          cols: 4,
          rows: 3,
          start: { x: 0, y: 1 },
          goal: { x: 3, y: 1 },
          walls: [],
          palette: [
            { dx: 1, dy: 0, times: 1 },
            { dx: -1, dy: 0, times: 1 },
            { dx: 0, dy: -1, times: 1 },
            { dx: 0, dy: 1, times: 1 },
          ],
          maxBlocks: null,
        },
        {
          kind: "robot",
          id: "cmd-turns",
          emoji: "🔀",
          title: { en: "The Big Turn", id: "Belokan Besar" },
          instructions: {
            en: "The star is up AND across! Mix up-arrows and right-arrows to reach it.",
            id: "Bintangnya di atas DAN menyamping! Gabungkan panah atas dan kanan untuk mencapainya.",
          },
          cols: 4,
          rows: 4,
          start: { x: 0, y: 3 },
          goal: { x: 3, y: 0 },
          walls: [],
          palette: [
            { dx: 1, dy: 0, times: 1 },
            { dx: -1, dy: 0, times: 1 },
            { dx: 0, dy: -1, times: 1 },
            { dx: 0, dy: 1, times: 1 },
          ],
          maxBlocks: null,
        },
        {
          kind: "robot",
          id: "cmd-treasure",
          emoji: "💎",
          title: { en: "The Treasure Climb", id: "Memanjat ke Harta" },
          instructions: {
            en: "The wall is in the way! Go up first, then across to the treasure star.",
            id: "Ada tembok menghalangi! Naik dulu, lalu menyamping ke bintang harta.",
          },
          cols: 4,
          rows: 4,
          start: { x: 0, y: 3 },
          goal: { x: 3, y: 0 },
          walls: [
            { x: 1, y: 2 },
            { x: 2, y: 2 },
            { x: 3, y: 2 },
          ],
          palette: [
            { dx: 1, dy: 0, times: 1 },
            { dx: -1, dy: 0, times: 1 },
            { dx: 0, dy: -1, times: 1 },
            { dx: 0, dy: 1, times: 1 },
          ],
          maxBlocks: null,
        },
        {
          kind: "robot",
          id: "cmd-exact",
          emoji: "🧱",
          title: { en: "Around the Wall", id: "Memutari Tembok" },
          instructions: {
            en: "A wall blocks the path and you may use at most 6 blocks! Psst — the ×2 block repeats a step but only counts as one.",
            id: "Tembok menghalangi jalan dan kamu hanya boleh pakai 6 balok! Psst — balok ×2 mengulang langkah tapi cuma dihitung satu.",
          },
          cols: 5,
          rows: 3,
          start: { x: 0, y: 1 },
          goal: { x: 4, y: 1 },
          walls: [{ x: 2, y: 1 }],
          palette: [
            { dx: 1, dy: 0, times: 1 },
            { dx: -1, dy: 0, times: 1 },
            { dx: 0, dy: -1, times: 1 },
            { dx: 0, dy: 1, times: 1 },
            { dx: 1, dy: 0, times: 2 },
          ],
          maxBlocks: 6,
        },
        {
          kind: "robot",
          id: "cmd-labyrinth",
          emoji: "🌀",
          title: { en: "The Grand Labyrinth", id: "Labirin Besar" },
          instructions: {
            en: "A twisting maze — and only 7 blocks allowed! You will need the repeat blocks (×2, ×3) to make it through.",
            id: "Labirin berliku — dan hanya boleh 7 balok! Kamu butuh balok ulang (×2, ×3) untuk bisa sampai.",
          },
          cols: 6,
          rows: 4,
          start: { x: 0, y: 3 },
          goal: { x: 5, y: 0 },
          walls: [
            { x: 1, y: 1 },
            { x: 1, y: 2 },
            { x: 1, y: 3 },
            { x: 3, y: 0 },
            { x: 3, y: 1 },
            { x: 3, y: 2 },
          ],
          palette: [
            { dx: 1, dy: 0, times: 1 },
            { dx: -1, dy: 0, times: 1 },
            { dx: 0, dy: -1, times: 1 },
            { dx: 0, dy: 1, times: 1 },
            { dx: 1, dy: 0, times: 2 },
            { dx: 0, dy: -1, times: 3 },
            { dx: 0, dy: 1, times: 3 },
          ],
          maxBlocks: 7,
        },
      ],
    },
    {
      id: "patterns",
      emoji: "🧩",
      color: "#3b82f6",
      title: { en: "Pattern Power", id: "Kekuatan Pola" },
      description: {
        en: "Programmers are great at spotting what repeats. Can you see the pattern?",
        id: "Programmer jago menemukan apa yang berulang. Bisakah kamu melihat polanya?",
      },
      games: [
        {
          kind: "pattern",
          id: "pat-colors",
          emoji: "🎈",
          title: { en: "Balloon Parade", id: "Parade Balon" },
          instructions: {
            en: "Look at the balloons. Which one comes next?",
            id: "Perhatikan balonnya. Mana yang berikutnya?",
          },
          sequence: ["🔴", "🔵", "🔴", "🔵", "🔴"],
          options: ["🔴", "🔵", "🟢"],
          answer: "🔵",
        },
        {
          kind: "pattern",
          id: "pat-shapes",
          emoji: "🚂",
          title: { en: "The Shape Train", id: "Kereta Bentuk" },
          instructions: {
            en: "Two squares, then a star. What comes next on the train?",
            id: "Dua kotak, lalu bintang. Apa gerbong berikutnya?",
          },
          sequence: ["🟦", "🟦", "⭐", "🟦", "🟦", "⭐", "🟦", "🟦"],
          options: ["🟦", "⭐", "🟥"],
          answer: "⭐",
        },
        {
          kind: "pattern",
          id: "pat-animals",
          emoji: "🎪",
          title: { en: "Animal Circus", id: "Sirkus Hewan" },
          instructions: {
            en: "The animals march in a pattern. Who marches next?",
            id: "Hewan-hewan berbaris dengan pola. Siapa yang berikutnya?",
          },
          sequence: ["🐱", "🐶", "🐶", "🐱", "🐶", "🐶", "🐱"],
          options: ["🐱", "🐶", "🐰"],
          answer: "🐶",
        },
        {
          kind: "pattern",
          id: "pat-fruits",
          emoji: "🍇",
          title: { en: "Fruit Salad", id: "Salad Buah" },
          instructions: {
            en: "Apple, banana, grapes — three friends repeat in a circle. Who comes next?",
            id: "Apel, pisang, anggur — tiga sahabat berulang bergiliran. Siapa berikutnya?",
          },
          sequence: ["🍎", "🍌", "🍇", "🍎", "🍌", "🍇", "🍎", "🍌"],
          options: ["🍎", "🍇", "🍌"],
          answer: "🍇",
        },
        {
          kind: "pattern",
          id: "pat-riddle",
          emoji: "🎭",
          title: { en: "The Tricky Parade", id: "Parade Penuh Teka-Teki" },
          instructions: {
            en: "Frog is everywhere! Look VERY closely at who walks between the frogs.",
            id: "Katak ada di mana-mana! Perhatikan baik-baik siapa yang berjalan di antara para katak.",
          },
          sequence: ["🐸", "🦊", "🐸", "🐢", "🐸", "🦊", "🐸"],
          options: ["🐸", "🦊", "🐢"],
          answer: "🐢",
        },
      ],
    },
    {
      id: "memory",
      emoji: "🎵",
      color: "#ec4899",
      title: { en: "Robo Says", id: "Kata Robo" },
      description: {
        en: "Robo plays a drum song. Watch closely, remember it, and play it back — exactly!",
        id: "Robo memainkan lagu drum. Perhatikan, ingat, lalu mainkan kembali — persis sama!",
      },
      games: [
        {
          kind: "memory",
          id: "mem-duo",
          emoji: "🥁",
          title: { en: "Drum Duo", id: "Duo Drum" },
          instructions: {
            en: "Watch Robo play, then tap the same drums in the same order!",
            id: "Lihat Robo bermain, lalu ketuk drum yang sama dengan urutan yang sama!",
          },
          pads: [
            { color: "#ef4444", emoji: "❤️" },
            { color: "#3b82f6", emoji: "⭐" },
          ],
          sequence: [0, 1],
        },
        {
          kind: "memory",
          id: "mem-trio",
          emoji: "🎶",
          title: { en: "Three Little Drums", id: "Tiga Drum Kecil" },
          instructions: {
            en: "One more drum joined the band. Can you copy the song?",
            id: "Satu drum lagi ikut bermain. Bisakah kamu meniru lagunya?",
          },
          pads: [
            { color: "#ef4444", emoji: "❤️" },
            { color: "#3b82f6", emoji: "⭐" },
            { color: "#22c55e", emoji: "🍀" },
          ],
          sequence: [0, 2, 1],
        },
        {
          kind: "memory",
          id: "mem-four-beats",
          emoji: "🎼",
          title: { en: "The Longer Song", id: "Lagu yang Lebih Panjang" },
          instructions: {
            en: "Four beats now — remember them all!",
            id: "Sekarang empat ketukan — ingat semuanya!",
          },
          pads: [
            { color: "#ef4444", emoji: "❤️" },
            { color: "#3b82f6", emoji: "⭐" },
            { color: "#22c55e", emoji: "🍀" },
          ],
          sequence: [2, 0, 1, 2],
        },
        {
          kind: "memory",
          id: "mem-band",
          emoji: "🪘",
          title: { en: "The Four Drum Band", id: "Band Empat Drum" },
          instructions: {
            en: "Four drums, five beats. Eyes on Robo!",
            id: "Empat drum, lima ketukan. Perhatikan Robo!",
          },
          pads: [
            { color: "#ef4444", emoji: "❤️" },
            { color: "#3b82f6", emoji: "⭐" },
            { color: "#22c55e", emoji: "🍀" },
            { color: "#eab308", emoji: "🌙" },
          ],
          sequence: [1, 3, 0, 2, 1],
        },
        {
          kind: "memory",
          id: "mem-concert",
          emoji: "🌟",
          title: { en: "The Grand Concert", id: "Konser Besar" },
          instructions: {
            en: "The final song has a sneaky double beat. Listen with your eyes!",
            id: "Lagu terakhir punya ketukan ganda yang licik. Dengarkan dengan matamu!",
          },
          pads: [
            { color: "#ef4444", emoji: "❤️" },
            { color: "#3b82f6", emoji: "⭐" },
            { color: "#22c55e", emoji: "🍀" },
            { color: "#eab308", emoji: "🌙" },
          ],
          sequence: [0, 2, 2, 3, 1, 0],
        },
      ],
    },
  ],
};
